theme: minima
title: The Discovery of India
author: Jawaharlal Nehru
description: The Discovery of India was written by the  Indian Independence leader Jawaharlal Nehru,during his imprisonment at Ahmednagar fort for participating in the Quit India Movement
